//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitesach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.Carts = new HashSet<Cart>();
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaSach { get; set; }
        [Display (Name ="Tên Sách")]
        public string TenSach { get; set; }
        [Display(Name = "Gía Gốc")]
        public Nullable<decimal> Giagoc { get; set; }
        [Display(Name = "Gía Bán")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô Tả")]
        public string MoTa { get; set; }
        [Display(Name = "ảnh")]
        public string AnhBia { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Số lượng đã bán")]
        public Nullable<int> SLdaban { get; set; }
        [Display(Name = "số lwooowjg tồn")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Mã NXB")]
        public Nullable<int> MaNXB { get; set; }
        [Display(Name = "Mã Chủ Đề")]
        public Nullable<int> MaChuDe { get; set; }
        [Display(Name = "Tên Mã Tác Gỉa")]
        public Nullable<int> MaTacGia { get; set; }
        [Display(Name = "Sách mới")]
        public Nullable<int> Moi { get; set; }
        [Display(Name = "yêu thích")]
        public Nullable<int> YeuThich { get; set; }
        [Display(Name = "Năm Xuất bản")]
        public Nullable<int> NaMXB { get; set; }
        [Display(Name = "Trọng lượng")]
        public string TrongLuong { get; set; }
        [Display(Name = "Kích thước")]
        public string KichThuoc { get; set; }
        [Display(Name = "Loại bìa")]
        public string LoaiBia { get; set; }
        [Display(Name = "số trang")]
        public Nullable<int> SoTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
